version: '3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: my-project-frontend
    restart: unless-stopped
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_STRAPI_API_URL=${NEXT_PUBLIC_STRAPI_API_URL:-http://localhost:1337}
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: my-project-backend
    restart: unless-stopped
    ports:
      - "${BACKEND_PORT:-1337}:1337"
    environment:
      - NODE_ENV=production
      - DATABASE_CLIENT=postgres
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=${POSTGRES_DB:-strapi}
      - DATABASE_USERNAME=${POSTGRES_USER:-strapi}
      - DATABASE_PASSWORD=${POSTGRES_PASSWORD:-strapi}
      - JWT_SECRET=${JWT_SECRET:-changeme}
      - ADMIN_JWT_SECRET=${ADMIN_JWT_SECRET:-changeme}
      - APP_KEYS=${APP_KEYS:-changeme1,changeme2,changeme3,changeme4}
      - API_TOKEN_SALT=${API_TOKEN_SALT:-changeme}
      - STRAPI_ADMIN_EMAIL=${STRAPI_ADMIN_EMAIL:-admin@example.com}
      - STRAPI_ADMIN_PASSWORD=${STRAPI_ADMIN_PASSWORD:-Admin123!}
      - STRAPI_ADMIN_FIRSTNAME=${STRAPI_ADMIN_FIRSTNAME:-Admin}
      - STRAPI_ADMIN_LASTNAME=${STRAPI_ADMIN_LASTNAME:-User}
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres:16
    container_name: my-project-postgres
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-strapi}
      - POSTGRES_USER=${POSTGRES_USER:-strapi}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-strapi}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data: 